sudo: false

language: node_js

node_js:
- stable

notifications:
  email: true
  slack: $SLACK_TOKEN

branches:
  only:
  - master

script:
- yarn build

deploy:
  skip_cleanup: true
  provider: npm
  email: cb@webhouse.dk
  api_key: $NPM_TOKEN
  on:
    repo: odeum/odeum-primitives
